
import { 
  LayoutDashboard, 
  Users, 
  BookOpen, 
  Calendar, 
  MessageSquare, 
  FileText, 
  Settings, 
  ShieldCheck, 
  Building, 
  CalendarClock,
  GraduationCap,
  University as UniIcon
} from 'lucide-react';
import { NavItem, StudentRecord, Teacher, University } from './types';

export const NAV_ITEMS: NavItem[] = [
  { id: 'dashboard', labelEn: 'Dashboard', labelZh: '仪表盘', icon: LayoutDashboard },
  { id: 'students', labelEn: 'Students & Profiles', labelZh: '学生档案', icon: Users },
  { id: 'academics', labelEn: 'Academic Records', labelZh: '学术管理', icon: BookOpen },
  { id: 'university_management', labelEn: 'Uni Management', labelZh: '大学管理', icon: UniIcon },
  { id: 'university_apps', labelEn: 'Uni Applications', labelZh: '大学申请', icon: GraduationCap },
  { id: 'consultations', labelEn: '1-1 Consultation', labelZh: '一对一咨询', icon: CalendarClock },
  { id: 'timetable', labelEn: 'Timetable', labelZh: '课程表', icon: Calendar },
  { id: 'attendance', labelEn: 'Attendance', labelZh: '出勤管理', icon: ShieldCheck },
  { id: 'hostel', labelEn: 'Hostel', labelZh: '宿舍管理', icon: Building },
  { id: 'reports', labelEn: 'Reports', labelZh: '报告生成', icon: FileText },
  { id: 'messages', labelEn: 'Messages', labelZh: '消息中心', icon: MessageSquare },
  { id: 'settings', labelEn: 'Settings', labelZh: '系统设置', icon: Settings },
];

export const MOCK_UNIVERSITIES: University[] = [
  {
    id: 'UNI001',
    name: 'Northeastern University',
    location: { city: 'Boston', state: 'Massachusetts', country: 'USA' },
    logo: 'https://images.unsplash.com/photo-1592285334235-ac149a1ff023?auto=format&fit=crop&w=200&h=200',
    banner: 'https://images.unsplash.com/photo-1541339907198-e08756ebafe3?auto=format&fit=crop&w=1200&q=80',
    description: 'Northeastern is a global research university and a world leader in experiential learning, with a focus on co-op education and practical experience.',
    type: 'Private',
    established: 1898,
    ranking: '#44 in National Universities (US News)',
    worldRanking: 44,
    averageTuition: '$62,000 / year',
    minGPA: '3.5',
    englishRequirement: 'IELTS 7.0 / TOEFL 100',
    features: ['Top-tier Co-op Program', 'R1 Research Institution', 'Global Campus Network'],
    programs: [
      { name: 'Computer Science', level: 'Masters', tuition: '$35,000', duration: '2 Years' },
      { name: 'Business Administration', level: 'Bachelors', tuition: '$62,000', duration: '4 Years' },
      { name: 'Electrical Engineering', level: 'Masters', tuition: '$38,000', duration: '1.5-2 Years' }
    ]
  },
  {
    id: 'UNI002',
    name: 'University of Malaya',
    location: { city: 'Kuala Lumpur', state: 'Federal Territory', country: 'Malaysia' },
    logo: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?auto=format&fit=crop&w=200&h=200',
    banner: 'https://images.unsplash.com/photo-1562774053-701939374585?auto=format&fit=crop&w=1200&q=80',
    description: 'The oldest and most prestigious university in Malaysia, UM is a top-ranked research university with a rich history and academic excellence.',
    type: 'Public',
    established: 1905,
    ranking: '#65 in QS Global World Rankings',
    worldRanking: 65,
    averageTuition: 'RM 15,000 / year (International)',
    minGPA: '3.0',
    englishRequirement: 'IELTS 6.0',
    features: ['Oldest University in Malaysia', 'High Research Output', 'Central KL Location'],
    programs: [
      { name: 'Medicine', level: 'Bachelors', tuition: 'RM 25,000', duration: '5 Years' },
      { name: 'Economics', level: 'Masters', tuition: 'RM 18,000', duration: '1.5 Years' }
    ]
  },
  {
    id: 'UNI003',
    name: 'National University of Singapore (NUS)',
    location: { city: 'Singapore', state: 'Singapore', country: 'Singapore' },
    logo: 'https://images.unsplash.com/photo-1498243639351-a6c9af99aef0?auto=format&fit=crop&w=200&h=200',
    banner: 'https://images.unsplash.com/photo-1517486808906-6ca8b3f04846?auto=format&fit=crop&w=1200&q=80',
    description: 'NUS is consistently ranked as one of the best universities in the world. It offers a global approach to education and research, with a focus on Asian perspectives and expertise.',
    type: 'Public',
    established: 1905,
    ranking: '#8 in QS World University Rankings',
    worldRanking: 8,
    averageTuition: '$30,000 / year (International)',
    minGPA: '3.8',
    englishRequirement: 'IELTS 7.5',
    features: ['Global Research Hub', 'Top in Asia', 'Diverse International Community'],
    programs: [
      { name: 'Data Science', level: 'Masters', tuition: '$45,000', duration: '1 Year' },
      { name: 'Architecture', level: 'Bachelors', tuition: '$35,000', duration: '5 Years' }
    ]
  },
  {
    id: 'UNI004',
    name: 'University of Melbourne',
    location: { city: 'Melbourne', state: 'Victoria', country: 'Australia' },
    logo: 'https://images.unsplash.com/photo-1541339907198-e08756ebafe3?auto=format&fit=crop&w=200&h=200',
    banner: 'https://images.unsplash.com/photo-1592285334235-ac149a1ff023?auto=format&fit=crop&w=1200&q=80',
    description: 'The University of Melbourne is a public research university in Australia. It is the second oldest university in Australia and the oldest in Victoria.',
    type: 'Public',
    established: 1853,
    ranking: '#14 in QS World University Rankings',
    worldRanking: 14,
    averageTuition: '$42,000 AUD / year',
    minGPA: '3.2',
    englishRequirement: 'IELTS 7.0',
    features: ['Research Excellence', 'Cultural Hub', 'Historic Campus'],
    programs: [
      { name: 'Law', level: 'Masters', tuition: '$50,000', duration: '3 Years' },
      { name: 'Arts', level: 'Bachelors', tuition: '$35,000', duration: '3 Years' }
    ]
  },
  {
    id: 'UNI005',
    name: 'University of Oxford',
    location: { city: 'Oxford', state: 'Oxfordshire', country: 'UK' },
    logo: 'https://images.unsplash.com/photo-1519452635265-7b1fbfd1e4e0?auto=format&fit=crop&w=200&h=200',
    banner: 'https://images.unsplash.com/photo-1527668752968-14dc70a27c95?auto=format&fit=crop&w=1200&q=80',
    description: 'Oxford is a unique and historic institution. As the oldest university in the English-speaking world, it can lay claim to nine centuries of continuous existence.',
    type: 'Public',
    established: 1096,
    ranking: '#3 in QS World University Rankings',
    worldRanking: 3,
    averageTuition: '£28,000 - £44,000 / year',
    minGPA: '3.9',
    englishRequirement: 'IELTS 7.5',
    features: ['World-renowned Reputation', 'Tutorial System', 'Rich History'],
    programs: [
      { name: 'Philosophy', level: 'Masters', tuition: '£30,000', duration: '1 Year' },
      { name: 'Politics', level: 'Bachelors', tuition: '£28,000', duration: '3 Years' }
    ]
  },
  {
    id: 'UNI006',
    name: 'University of British Columbia (UBC)',
    location: { city: 'Vancouver', state: 'British Columbia', country: 'Canada' },
    logo: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?auto=format&fit=crop&w=200&h=200',
    banner: 'https://images.unsplash.com/photo-1565034946487-077786996e27?auto=format&fit=crop&w=1200&q=80',
    description: 'UBC is a global center for teaching, learning and research, consistently ranked among the top 20 public universities in the world.',
    type: 'Public',
    established: 1908,
    ranking: '#34 in QS World University Rankings',
    worldRanking: 34,
    averageTuition: '$40,000 CAD / year',
    minGPA: '3.4',
    englishRequirement: 'IELTS 6.5',
    features: ['Ocean-front Campus', 'Sustainable Research', 'Strong Alumni Network'],
    programs: [
      { name: 'Marine Biology', level: 'Masters', tuition: '$25,000', duration: '2 Years' },
      { name: 'Commerce', level: 'Bachelors', tuition: '$40,000', duration: '4 Years' }
    ]
  }
];

export const MOCK_TEACHERS: Teacher[] = [
  { id: 'T001', name: 'Mrs. Sarah Anderson', subject: 'Mathematics', avatar: 'https://picsum.photos/id/40/200/200', officeLocation: 'Room 304, Block A', availableDays: [1, 3, 5] },
  { id: 'T002', name: 'Mr. John Smith', subject: 'Physics', avatar: 'https://picsum.photos/id/55/200/200', officeLocation: 'Science Lab 2', availableDays: [2, 4] },
  { id: 'T003', name: 'Ms. Emily Blunt', subject: 'English Literature', avatar: 'https://picsum.photos/id/65/200/200', officeLocation: 'Library Office', availableDays: [1, 2, 3, 4, 5] },
  { id: 'T004', name: 'Dr. Alan Grant', subject: 'History', avatar: 'https://picsum.photos/id/75/200/200', officeLocation: 'Room 102, Block B', availableDays: [3, 5] },
];

export const MOCK_STUDENTS: StudentRecord[] = [
  {
    id: 'STU001',
    name: 'Alice Chen',
    email: 'alice.chen@smartsis.edu',
    className: 'Class 10-A',
    avatar: 'https://picsum.photos/id/64/200/200',
    grade: 'Year 10',
    attendanceRate: 98,
    enrollmentDate: '2022-09-01',
    expectedGraduationDate: '2025-06-30',
    status: 'Active',
    results: [
      { 
        semester: 'Fall 2023', 
        subject: 'Mathematics', 
        score: 92, 
        monthlyScores: [
          { month: 'September', score: 88, comment: 'Great start!' },
          { month: 'October', score: 94, comment: 'Improved significantly.' },
          { month: 'November', score: 94 },
          { month: 'December', score: 92, comment: 'Consistent performance.' }
        ],
        date: '2023-12-15', 
        teacherComment: 'Alice shows exceptional problem-solving skills, particularly in calculus.' 
      },
      { 
        semester: 'Fall 2023', 
        subject: 'History', 
        score: 85, 
        monthlyScores: [
          { month: 'September', score: 82, comment: 'Needs more detail in essays.' },
          { month: 'October', score: 85 },
          { month: 'November', score: 88, comment: 'Much better analysis.' }
        ],
        date: '2023-12-18', 
        teacherComment: 'Good understanding of historical contexts, but needs to improve essay structure.' 
      },
      { semester: 'Spring 2024', subject: 'Science', score: 88, monthlyScores: [{ month: 'Feb', score: 88 }], date: '2024-05-20', teacherComment: 'Consistently performs well in lab experiments.' },
      { semester: 'Spring 2024', subject: 'Mathematics', score: 95, monthlyScores: [{ month: 'Feb', score: 95 }], date: '2024-05-22', teacherComment: 'Perfect score in final algebra test.' }
    ],
    activities: ['Debate Club', 'Swimming Team']
  },
  {
    id: 'STU002',
    name: 'Michael Wang',
    email: 'michael.wang@smartsis.edu',
    className: 'Class 11-B',
    avatar: 'https://picsum.photos/id/91/200/200',
    grade: 'Year 11',
    attendanceRate: 85,
    enrollmentDate: '2021-09-01',
    expectedGraduationDate: '2024-06-30',
    status: 'Active',
    results: [
      { semester: 'Fall 2023', subject: 'Mathematics', score: 78, monthlyScores: [{ month: 'Sep', score: 75, comment: 'struggling with algebra' }, { month: 'Oct', score: 81 }], date: '2023-12-15', teacherComment: 'Michael is making steady progress but struggles with algebraic concepts.' },
      { semester: 'Fall 2023', subject: 'History', score: 95, monthlyScores: [{ month: 'Sep', score: 92 }, { month: 'Oct', score: 98 }], date: '2023-12-18', teacherComment: 'Outstanding performance. His analysis of the industrial revolution was insightful.' },
      { semester: 'Spring 2024', subject: 'Mathematics', score: 82, monthlyScores: [{ month: 'Feb', score: 82 }], date: '2024-05-15', teacherComment: 'Showed improvement in geometry.' }
    ],
    activities: ['Chess Club']
  },
  {
    id: 'STU003',
    name: 'Sarah Johnson',
    email: 'sarah.j@smartsis.edu',
    className: 'Class 10-A',
    avatar: 'https://picsum.photos/id/129/200/200',
    grade: 'Year 10',
    attendanceRate: 92,
    enrollmentDate: '2022-09-01',
    expectedGraduationDate: '2025-06-30',
    status: 'Active',
    results: [
      { semester: 'Fall 2023', subject: 'Mathematics', score: 88, monthlyScores: [{ month: 'Sep', score: 88 }], date: '2023-12-15', teacherComment: 'Sarah participates actively in class and helps her peers.' },
      { semester: 'Fall 2023', subject: 'Science', score: 91, monthlyScores: [{ month: 'Sep', score: 91 }], date: '2023-12-20', teacherComment: 'Excellent attention to detail in biology.' }
    ],
    activities: ['Drama Club', 'Choir']
  },
  {
    id: 'STU004',
    name: 'David Li',
    email: 'david.li@smartsis.edu',
    className: 'Class 12-C',
    avatar: 'https://picsum.photos/id/177/200/200',
    grade: 'Year 12',
    attendanceRate: 99,
    enrollmentDate: '2020-09-01',
    expectedGraduationDate: '2023-06-30',
    status: 'Active',
    results: [
      { semester: 'Fall 2023', subject: 'Mathematics', score: 98, monthlyScores: [{ month: 'Sep', score: 98 }, { month: 'Oct', score: 98 }], date: '2023-12-15', teacherComment: 'A perfect score. David is ready for university-level mathematics.' },
      { semester: 'Spring 2024', subject: 'Mathematics', score: 99, monthlyScores: [{ month: 'Feb', score: 99 }], date: '2024-05-15', teacherComment: 'Continues to dominate the leaderboard.' }
    ],
    activities: ['Robotics', 'Student Council']
  }
];

export const UI_LABELS = {
  en: {
    welcome: 'Welcome back',
    viewProfile: 'View Profile',
    search: 'Search students...',
    translate: 'Translate to Chinese',
    original: 'Show Original',
    chatPlaceholder: 'Ask AI assistant about school policies...',
    sendMessage: 'Send',
    attendanceTrend: 'Attendance Trend',
    gradeDistribution: 'Grade Distribution',
    activeStudents: 'Active Students',
    avgAttendance: 'Avg. Attendance',
    totalCourses: 'Total Courses',
    pendingApprovals: 'Pending Approvals',
    recentActivity: 'Recent Activity',
    academicRecords: 'Academic Records',
    teacherComment: 'Teacher Comment',
    score: 'Score',
    timetable: 'Timetable',
    hostelOverview: 'Hostel Overview',
    settings: 'Settings',
    save: 'Save Changes',
    general: 'General',
    notifications: 'Notifications',
    occupancyRate: 'Occupancy Rate',
    maintenanceRequests: 'Maintenance Requests',
    roomAllocation: 'Room Allocation',
    markAttendance: 'Mark Attendance',
    classSelect: 'Select Class',
    present: 'Present',
    absent: 'Absent',
    late: 'Late',
    excused: 'Excused',
    saveAttendance: 'Save Record',
    remarks: 'Remarks',
    loginTitle: 'Sign in to Smart SIS',
    loginSubtitle: 'Welcome back! Please enter your details.',
    email: 'Email',
    password: 'Password',
    signIn: 'Sign in',
    signingIn: 'Signing in...',
    logout: 'Log out',
    forgotPassword: 'Forgot password?',
    reportsTitle: 'Reports Center',
    generateReport: 'Generate Report',
    recentReports: 'Recent Reports',
    reportType: 'Report Type',
    generatedDate: 'Generated Date',
    status: 'Status',
    download: 'Download',
    ready: 'Ready',
    processing: 'Processing',
    academicPerformance: 'Academic Performance',
    attendanceSummary: 'Attendance Summary',
    hostelOccupancy: 'Hostel Occupancy',
    financialReport: 'Financial Report',
    studentList: 'Student List',
    name: 'Name',
    studentId: 'Student ID',
    className: 'Class',
    enrollmentDate: 'Enrollment Date',
    expectedGraduationDate: 'Expected Graduation',
    actions: 'Actions',
    averageScore: 'Average Score',
    overallGrade: 'Overall Grade',
    subjectPerformance: 'Subject Performance',
    classAverage: 'Class Average',
    topPerformer: 'Top Performer',
    typeMessage: 'Type a message...',
    conversations: 'Conversations',
    online: 'Online',
    offline: 'Offline',
    noMessages: 'No messages yet',
    selectConversation: 'Select a conversation to start messaging',
    activeSubjects: 'Active Subjects',
    needsAttention: 'Needs Attention',
    exportGrades: 'Export Grades',
    performanceInsights: 'Performance Insights',
    showing: 'Showing',
    studentsSuffix: 'students',
    noRecordsFound: 'No records found matching your filters.',
    avgScoreChart: 'Avg Score',
    insightMath: 'Mathematics has the highest average score',
    insightHistory: 'History scores have improved by 5% compared to last month.',
    insightScience: 'Science practicals are scheduled for next week.',
    semesterSuffix: 'this semester',
    exportCSV: 'Export CSV',
    semester: 'Semester',
    allSemesters: 'All Semesters',
    backToRecords: 'Back to Records',
    studentAcademicProfile: 'Academic Profile',
    subject: 'Subject',
    date: 'Date',
    grade: 'Grade',
    preview: 'Preview',
    reportPreview: 'Report Preview',
    close: 'Close',
    print: 'Print',
    behaviorReport: 'Behavior Report',
    manageMonthly: 'Manage Monthly Exams',
    monthlyBreakdown: 'Monthly Exam Breakdown',
    month: 'Month',
    enterScore: 'Enter Score',
    totalCalculated: 'Total Score (Avg)',
    addComment: 'Add Comment',
    semesterReport: 'Semester Report Card',
    generatedOn: 'Generated on',
    principalSignature: 'Principal Signature',
    classTeacherSignature: 'Class Teacher Signature',
    schoolHeader: 'Smart SIS High School',
    commentsSection: 'Teacher Comments & Remarks',
    // Consultations
    consultationTitle: '1-1 Consultation',
    selectTeacher: 'Select a Teacher',
    selectDateTime: 'Select a Date & Time',
    availableSlots: 'Available Slots',
    confirmBooking: 'Confirm',
    duration: '30 min',
    location: 'Location',
    bookingConfirmed: 'Booking Confirmed!',
    bookingSubtitle: 'Your session has been scheduled successfully.',
    backToTeachers: 'Back to Teachers',
    // University Management
    uniManagementTitle: 'University Management',
    addUniversity: 'Add University',
    editUniversity: 'Edit University',
    uniName: 'University Name',
    uniLocation: 'Location',
    uniType: 'Institution Type',
    uniEstablished: 'Established Year',
    uniRanking: 'Global Ranking',
    uniDescription: 'Description',
    uniTuition: 'Avg. Tuition',
    uniRequirements: 'Admission Requirements',
    uniPrograms: 'Available Programs',
    uniFeatures: 'Key Features',
    uniLogo: 'Logo URL',
    uniBanner: 'Banner Image URL',
    saveUniversity: 'Save University Info',
    backToUniList: 'Back to University List',
    programName: 'Program Name',
    programLevel: 'Level',
    programTuition: 'Tuition Fee',
    programDuration: 'Duration',
    addProgram: 'Add Program',
    requirementGPA: 'Minimum GPA',
    requirementEnglish: 'English Requirement',
    allCountries: 'All Countries',
    allTypes: 'All Types',
    rankingTop50: 'Top 50',
    rankingTop100: 'Top 100',
    rankingAll: 'All Rankings',
    // University Applications Refactor
    uniAppTitle: 'University Hub',
    myProfile: 'Student Admission Profile',
    browseUniversities: 'Explore & Apply',
    myApplications: 'Application Tracker',
    updateProfile: 'Save Profile Information',
    newApplication: 'Create New Application',
    selectProgram: 'Select Desired Program',
    reviewAndSubmit: 'Review & Submit Application',
    stepPersonal: 'Personal Information',
    stepContact: 'Contact Details',
    stepAcademic: 'Academic Background',
    stepEmergency: 'Emergency Contacts',
    stepUpload: 'Required Documents',
    // Fields
    surname: 'Surname',
    givenName: 'Given Name',
    dob: 'Date of Birth',
    nationality: 'Nationality',
    religion: 'Religion',
    icPassport: 'IC / Passport No.',
    passportExpiry: 'Passport Expiry Date',
    languages: 'Languages Spoken',
    mobile: 'Mobile Number',
    homeAddress: 'Home Address',
    emergencyContactName: 'Emergency Contact Name',
    emergencyRelationship: 'Relationship',
    emergencyPhone: 'Emergency Phone',
    highestQualification: 'Highest Qualification',
    gpa: 'GPA / Result',
    englishProficiency: 'English Proficiency',
    university: 'University',
    program: 'Program of Interest',
    intake: 'Intake Period',
    uploadPhoto: 'Upload Photo',
    uploadIC: 'Upload IC/Passport Copy',
    uploadResults: 'Upload Academic Results',
    uploadEnglish: 'Upload English Proficiency Proof',
    dropFiles: 'Drop files here or click to upload',
    submitApp: 'Submit University Application',
    appliedOn: 'Applied On',
  },
  zh: {
    welcome: '欢迎回来',
    viewProfile: '查看档案',
    search: '搜索学生...',
    translate: '翻译成中文',
    original: '显示原文',
    chatPlaceholder: '询问AI助手关于学校政策...',
    sendMessage: '发送',
    attendanceTrend: '出勤趋势',
    gradeDistribution: '成绩分布',
    activeStudents: '在校学生',
    avgAttendance: '平均出勤率',
    totalCourses: '课程总数',
    pendingApprovals: '待审批事项',
    recentActivity: '最近活动',
    academicRecords: '学术记录',
    teacherComment: '老师评语',
    score: '分数',
    timetable: '课程表',
    hostelOverview: '宿舍概览',
    settings: '设置',
    save: '保存更改',
    general: '常规',
    notifications: '通知',
    occupancyRate: '入住率',
    maintenanceRequests: '维修申请',
    roomAllocation: '房间分配',
    markAttendance: '考勤登记',
    classSelect: '选择班级',
    present: '出席',
    absent: '缺席',
    late: '迟到',
    excused: '请假',
    saveAttendance: '保存记录',
    remarks: '备注',
    loginTitle: '登录 Smart SIS',
    loginSubtitle: '欢迎回来！请输入您的详细信息。',
    email: '电子邮件',
    password: '密码',
    signIn: '登录',
    signingIn: '登录中...',
    logout: '退出登录',
    forgotPassword: '忘记密码？',
    reportsTitle: '报告中心',
    generateReport: '生成报告',
    recentReports: '最近报告',
    reportType: '报告类型',
    generatedDate: '生成日期',
    status: '状态',
    download: '下载',
    ready: '完成',
    processing: '处理中',
    academicPerformance: '学业成绩',
    attendanceSummary: '出勤总结',
    hostelOccupancy: '宿舍状态',
    financialReport: '财务报告',
    studentList: '学生列表',
    name: '姓名',
    studentId: '学号',
    className: '班级',
    enrollmentDate: '入学日期',
    expectedGraduationDate: '预计毕业日期',
    actions: '操作',
    averageScore: '平均分',
    overallGrade: '总评级',
    subjectPerformance: '学科表现',
    classAverage: '班级平均',
    topPerformer: '最佳表现',
    typeMessage: '输入消息...',
    conversations: '对话列表',
    online: '在线',
    offline: '离线',
    noMessages: '暂无消息',
    selectConversation: '选择一个对话开始聊天',
    activeSubjects: '活跃科目',
    needsAttention: '需关注',
    exportGrades: '导出成绩',
    performanceInsights: '表现洞察',
    showing: '显示',
    studentsSuffix: '名学生',
    noRecordsFound: '未找到符合条件的记录。',
    avgScoreChart: '平均分',
    insightMath: '数学是本学期平均分最高的科目',
    insightHistory: '历史成绩比上个月提高了 5%。',
    insightScience: '科学实验课安排在下周。',
    semesterSuffix: '',
    exportCSV: '导出 CSV',
    semester: '学期',
    allSemesters: '所有学期',
    backToRecords: '返回列表',
    studentAcademicProfile: '学生成绩档案',
    subject: '科目',
    date: '日期',
    grade: '等级',
    preview: '预览',
    reportPreview: '报告预览',
    close: '关闭',
    print: '打印',
    behaviorReport: '行为报告',
    manageMonthly: '月考管理',
    monthlyBreakdown: '月考成绩详情',
    month: '月份',
    enterScore: '输入分数',
    totalCalculated: '总成绩 (平均)',
    addComment: '添加评语',
    semesterReport: '学期成绩报告单',
    generatedOn: '生成日期',
    principalSignature: '校长签名',
    classTeacherSignature: '班主任签名',
    schoolHeader: 'Smart SIS 高级中学',
    commentsSection: '教师评语与备注',
    // Consultations
    consultationTitle: '一对一咨询',
    selectTeacher: '选择教师',
    selectDateTime: '选择日期与时间',
    availableSlots: '可用时段',
    confirmBooking: '确认预约',
    duration: '30分钟',
    location: '地点',
    bookingConfirmed: '预约成功！',
    bookingSubtitle: '您的咨询已成功安排。',
    backToTeachers: '返回教师列表',
    // University Management
    uniManagementTitle: '高校管理',
    addUniversity: '添加大学',
    editUniversity: '编辑大学信息',
    uniName: '学校名称',
    uniLocation: '地理位置',
    uniType: '办学类型',
    uniEstablished: '创办年份',
    uniRanking: '全球排名',
    uniDescription: '学校简介',
    uniTuition: '平均学费',
    uniRequirements: '录取要求',
    uniPrograms: '开设项目',
    uniFeatures: '办学特色',
    uniLogo: 'Logo 地址',
    uniBanner: '展示图地址',
    saveUniversity: '保存大学信息',
    backToUniList: '返回高校列表',
    programName: '项目名称',
    programLevel: '学位级别',
    programTuition: '学费',
    programDuration: '时长',
    addProgram: '添加项目',
    requirementGPA: '最低 GPA',
    requirementEnglish: '语言要求',
    allCountries: '所有国家',
    allTypes: '所有类型',
    rankingTop50: '前 50 名',
    rankingTop100: '前 100 名',
    rankingAll: '全部排名',
    // University Applications Refactor
    uniAppTitle: '大学中心',
    myProfile: '学生入学档案',
    browseUniversities: '探索与申请',
    myApplications: '申请追踪',
    updateProfile: '保存档案信息',
    newApplication: '创建新申请',
    selectProgram: '选择意向专业',
    reviewAndSubmit: '预览并提交申请',
    stepPersonal: '个人信息',
    stepContact: '联系方式',
    stepAcademic: '学术背景',
    stepEmergency: '紧急联系人',
    stepUpload: '所需文件',
    // Fields
    surname: '姓',
    givenName: '名',
    dob: '出生日期',
    nationality: '国籍',
    religion: '宗教',
    icPassport: '身份证/护照号码',
    passportExpiry: '护照到期日',
    languages: '使用语言',
    mobile: '手机号码',
    homeAddress: '家庭住址',
    emergencyContactName: '紧急联系人姓名',
    emergencyRelationship: '关系',
    emergencyPhone: '紧急联系电话',
    highestQualification: '最高学历',
    gpa: '平均分/成绩',
    englishProficiency: '英语水平',
    university: '申请院校',
    program: '意向专业',
    intake: '入学时段',
    uploadPhoto: '上传照片',
    uploadIC: '上传身份证/护照复印件',
    uploadResults: '上传学术成绩',
    uploadEnglish: '上传英语能力证明',
    dropFiles: '拖拽文件至此或点击上传',
    submitApp: '提交大学申请',
    appliedOn: '申请日期',
  }
};
