import { 
  LayoutDashboard, 
  Users, 
  BookOpen, 
  Calendar, 
  MessageSquare, 
  FileText, 
  Settings,
  ShieldCheck,
  Building
} from 'lucide-react';
import { NavItem, StudentRecord } from './types';

export const NAV_ITEMS: NavItem[] = [
  { id: 'dashboard', labelEn: 'Dashboard', labelZh: '仪表盘', icon: LayoutDashboard },
  { id: 'students', labelEn: 'Students & Profiles', labelZh: '学生档案', icon: Users },
  { id: 'academics', labelEn: 'Academic Records', labelZh: '学术管理', icon: BookOpen },
  { id: 'timetable', labelEn: 'Timetable', labelZh: '课程表', icon: Calendar },
  { id: 'attendance', labelEn: 'Attendance', labelZh: '出勤管理', icon: ShieldCheck },
  { id: 'hostel', labelEn: 'Hostel', labelZh: '宿舍管理', icon: Building },
  { id: 'reports', labelEn: 'Reports', labelZh: '报告生成', icon: FileText },
  { id: 'messages', labelEn: 'Messages', labelZh: '消息中心', icon: MessageSquare },
  { id: 'settings', labelEn: 'Settings', labelZh: '系统设置', icon: Settings },
];

export const MOCK_STUDENTS: StudentRecord[] = [
  {
    id: 'STU001',
    name: 'Alice Chen',
    email: 'alice.chen@smartsis.edu',
    className: 'Class 10-A',
    avatar: 'https://picsum.photos/id/64/200/200',
    grade: 'Year 10',
    attendanceRate: 98,
    enrollmentDate: '2022-09-01',
    expectedGraduationDate: '2025-06-30',
    status: 'Active',
    results: [
      { subject: 'Mathematics', score: 92, date: '2023-12-15', teacherComment: 'Alice shows exceptional problem-solving skills, particularly in calculus.' },
      { subject: 'History', score: 85, date: '2023-12-18', teacherComment: 'Good understanding of historical contexts, but needs to improve essay structure.' },
      { subject: 'Science', score: 88, date: '2023-12-20', teacherComment: 'Consistently performs well in lab experiments.' }
    ],
    activities: ['Debate Club', 'Swimming Team']
  },
  {
    id: 'STU002',
    name: 'Michael Wang',
    email: 'michael.wang@smartsis.edu',
    className: 'Class 11-B',
    avatar: 'https://picsum.photos/id/91/200/200',
    grade: 'Year 11',
    attendanceRate: 85,
    enrollmentDate: '2021-09-01',
    expectedGraduationDate: '2024-06-30',
    status: 'Active',
    results: [
      { subject: 'Mathematics', score: 78, date: '2023-12-15', teacherComment: 'Michael is making steady progress but struggles with algebraic concepts.' },
      { subject: 'History', score: 95, date: '2023-12-18', teacherComment: 'Outstanding performance. His analysis of the industrial revolution was insightful.' }
    ],
    activities: ['Chess Club']
  },
  {
    id: 'STU003',
    name: 'Sarah Johnson',
    email: 'sarah.j@smartsis.edu',
    className: 'Class 10-A',
    avatar: 'https://picsum.photos/id/129/200/200',
    grade: 'Year 10',
    attendanceRate: 92,
    enrollmentDate: '2022-09-01',
    expectedGraduationDate: '2025-06-30',
    status: 'Active',
    results: [
      { subject: 'Mathematics', score: 88, date: '2023-12-15', teacherComment: 'Sarah participates actively in class and helps her peers.' },
      { subject: 'Science', score: 91, date: '2023-12-20', teacherComment: 'Excellent attention to detail in biology.' }
    ],
    activities: ['Drama Club', 'Choir']
  },
  {
    id: 'STU004',
    name: 'David Li',
    email: 'david.li@smartsis.edu',
    className: 'Class 12-C',
    avatar: 'https://picsum.photos/id/177/200/200',
    grade: 'Year 12',
    attendanceRate: 99,
    enrollmentDate: '2020-09-01',
    expectedGraduationDate: '2023-06-30',
    status: 'Active',
    results: [
      { subject: 'Mathematics', score: 98, date: '2023-12-15', teacherComment: 'A perfect score. David is ready for university-level mathematics.' }
    ],
    activities: ['Robotics', 'Student Council']
  }
];

export const UI_LABELS = {
  en: {
    welcome: 'Welcome back',
    viewProfile: 'View Profile',
    search: 'Search students...',
    translate: 'Translate to Chinese',
    original: 'Show Original',
    chatPlaceholder: 'Ask AI assistant about school policies...',
    sendMessage: 'Send',
    attendanceTrend: 'Attendance Trend',
    gradeDistribution: 'Grade Distribution',
    activeStudents: 'Active Students',
    avgAttendance: 'Avg. Attendance',
    totalCourses: 'Total Courses',
    pendingApprovals: 'Pending Approvals',
    recentActivity: 'Recent Activity',
    academicRecords: 'Academic Records',
    teacherComment: 'Teacher Comment',
    score: 'Score',
    timetable: 'Timetable',
    hostelOverview: 'Hostel Overview',
    settings: 'Settings',
    save: 'Save Changes',
    general: 'General',
    notifications: 'Notifications',
    occupancyRate: 'Occupancy Rate',
    maintenanceRequests: 'Maintenance Requests',
    roomAllocation: 'Room Allocation',
    markAttendance: 'Mark Attendance',
    classSelect: 'Select Class',
    present: 'Present',
    absent: 'Absent',
    late: 'Late',
    excused: 'Excused',
    saveAttendance: 'Save Record',
    remarks: 'Remarks',
    loginTitle: 'Sign in to Smart SIS',
    loginSubtitle: 'Welcome back! Please enter your details.',
    email: 'Email',
    password: 'Password',
    signIn: 'Sign in',
    signingIn: 'Signing in...',
    logout: 'Log out',
    forgotPassword: 'Forgot password?',
    reportsTitle: 'Reports Center',
    generateReport: 'Generate Report',
    recentReports: 'Recent Reports',
    reportType: 'Report Type',
    generatedDate: 'Generated Date',
    status: 'Status',
    download: 'Download',
    ready: 'Ready',
    processing: 'Processing',
    academicPerformance: 'Academic Performance',
    attendanceSummary: 'Attendance Summary',
    hostelOccupancy: 'Hostel Occupancy',
    financialReport: 'Financial Report',
    studentList: 'Student List',
    name: 'Name',
    studentId: 'Student ID',
    className: 'Class',
    enrollmentDate: 'Enrollment Date',
    expectedGraduationDate: 'Expected Graduation',
    actions: 'Actions',
    averageScore: 'Average Score',
    overallGrade: 'Overall Grade',
    subjectPerformance: 'Subject Performance',
    classAverage: 'Class Average',
    topPerformer: 'Top Performer',
    typeMessage: 'Type a message...',
    conversations: 'Conversations',
    online: 'Online',
    offline: 'Offline',
    noMessages: 'No messages yet',
    selectConversation: 'Select a conversation to start messaging',
    // New Labels for Academic Records & Insights
    activeSubjects: 'Active Subjects',
    needsAttention: 'Needs Attention',
    exportGrades: 'Export Grades',
    performanceInsights: 'Performance Insights',
    showing: 'Showing',
    studentsSuffix: 'students',
    noRecordsFound: 'No records found matching your filters.',
    avgScoreChart: 'Avg Score',
    insightMath: 'Mathematics has the highest average score',
    insightHistory: 'History scores have improved by 5% compared to last month.',
    insightScience: 'Science practicals are scheduled for next week.',
    semesterSuffix: 'this semester',
  },
  zh: {
    welcome: '欢迎回来',
    viewProfile: '查看档案',
    search: '搜索学生...',
    translate: '翻译成中文',
    original: '显示原文',
    chatPlaceholder: '询问AI助手关于学校政策...',
    sendMessage: '发送',
    attendanceTrend: '出勤趋势',
    gradeDistribution: '成绩分布',
    activeStudents: '在校学生',
    avgAttendance: '平均出勤率',
    totalCourses: '课程总数',
    pendingApprovals: '待审批事项',
    recentActivity: '最近活动',
    academicRecords: '学术记录',
    teacherComment: '老师评语',
    score: '分数',
    timetable: '课程表',
    hostelOverview: '宿舍概览',
    settings: '设置',
    save: '保存更改',
    general: '常规',
    notifications: '通知',
    occupancyRate: '入住率',
    maintenanceRequests: '维修申请',
    roomAllocation: '房间分配',
    markAttendance: '考勤登记',
    classSelect: '选择班级',
    present: '出席',
    absent: '缺席',
    late: '迟到',
    excused: '请假',
    saveAttendance: '保存记录',
    remarks: '备注',
    loginTitle: '登录 Smart SIS',
    loginSubtitle: '欢迎回来！请输入您的详细信息。',
    email: '电子邮件',
    password: '密码',
    signIn: '登录',
    signingIn: '登录中...',
    logout: '退出登录',
    forgotPassword: '忘记密码？',
    reportsTitle: '报告中心',
    generateReport: '生成报告',
    recentReports: '最近报告',
    reportType: '报告类型',
    generatedDate: '生成日期',
    status: '状态',
    download: '下载',
    ready: '完成',
    processing: '处理中',
    academicPerformance: '学业成绩',
    attendanceSummary: '出勤总结',
    hostelOccupancy: '宿舍状态',
    financialReport: '财务报告',
    studentList: '学生列表',
    name: '姓名',
    studentId: '学号',
    className: '班级',
    enrollmentDate: '入学日期',
    expectedGraduationDate: '预计毕业日期',
    actions: '操作',
    averageScore: '平均分',
    overallGrade: '总评级',
    subjectPerformance: '学科表现',
    classAverage: '班级平均',
    topPerformer: '最佳表现',
    typeMessage: '输入消息...',
    conversations: '对话列表',
    online: '在线',
    offline: '离线',
    noMessages: '暂无消息',
    selectConversation: '选择一个对话开始聊天',
    // New Labels for Academic Records & Insights
    activeSubjects: '活跃科目',
    needsAttention: '需关注',
    exportGrades: '导出成绩',
    performanceInsights: '表现洞察',
    showing: '显示',
    studentsSuffix: '名学生',
    noRecordsFound: '未找到符合条件的记录。',
    avgScoreChart: '平均分',
    insightMath: '数学是本学期平均分最高的科目',
    insightHistory: '历史成绩比上个月提高了 5%。',
    insightScience: '科学实验课安排在下周。',
    semesterSuffix: '',
  }
};